services:
  rtmp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: local-nginx-rtmp
    ports:
      - "1935:1935"   # RTMP port
      - "8080:8080"   # HTTP status/landing page
    restart: unless-stopped